name: xkcdpass
version: 1.0
summary: xkcd password generator
description: Generate secure multiword passwords/passphrases, inspired by XKCD

grade: stable
confinement: strict

apps:
  xkcdpass:
    command: bin/xkcdpass

parts:
  xkcdpassgen:
    plugin: python
    source: https://github.com/redacted/XKCD-password-generator.git
